# Generated by Django 6.0 on 2025-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_options_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(null=True, to="store.product"),
        ),
    ]
