# Generated by Django 6.0 on 2025-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="carts", to="store.product"
            ),
        ),
    ]
