# Generated by Django 6.0 on 2025-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_orderitem_payment_shippingaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("esewa", "eSewa"),
                    ("khalti", "Khalti"),
                ],
                default="khalti",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
