# Generated by Django 6.0 on 2025-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_payment_method_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pidx",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
