# Generated by Django 6.0 on 2025-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_payment_pidx"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="purchase_order_id",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
