# Generated by Django 6.0 on 2025-12-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_deliveryperson_approved_at_deliveryperson_is_active_and_more",
        ),
        ("store", "0013_payment_purchase_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="accounts.deliveryperson",
            ),
        ),
    ]
