# Generated by Django 6.0 on 2025-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_order_delivery_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("on_the_way", "On the way"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
