# Generated by Django 6.0 on 2025-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
