# Generated by Django 6.0 on 2025-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.TextField(
                choices=[
                    ("admin", "Admin"),
                    ("delivery_person", "Delivery Person"),
                    ("customer", "Customer"),
                ],
                default="customer",
            ),
        ),
    ]
