# Generated by Django 6.0 on 2025-12-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField(help_text="Date of birth of Delivery Person")),
                (
                    "phone_number",
                    models.CharField(help_text="Normal contact", max_length=15),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        help_text="Contact number for emergency cases", max_length=15
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "citizenship",
                    models.FileField(
                        blank=True,
                        help_text="front and back side of the citizenship card in a pdf format",
                        null=True,
                        upload_to="delivery_person/citizenships/",
                    ),
                ),
                (
                    "driving_license",
                    models.ImageField(
                        blank=True,
                        help_text="Clear scanned image of driving license",
                        null=True,
                        upload_to="delivery_person/driving_licenses/",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bicycle", "Bicycle"),
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_plate_number", models.CharField(max_length=20)),
                (
                    "vehicle_color",
                    models.CharField(
                        blank=True,
                        default="black",
                        help_text="color of the vehicle",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
