# Generated by Django 6.0 on 2025-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_deliveryperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("delivery_person", "Delivery Person"),
                    ("inventory_staff", "Inventory Staff"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
