# Generated by Django 6.0 on 2025-12-22 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_deliveryperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliveryperson",
            name="vehicle_color",
            field=models.CharField(
                blank=True,
                default="black",
                help_text="Color of the vehicle",
                max_length=30,
                null=True,
            ),
        ),
    ]
